"""
Automatically categorize incoming customer support requests into predefined categories such as technical issues, billing inquiries, product questions, complaints, feature requests, or account management to enable proper routing and prioritization

This module implements a classification problem for LangChain optimization
using the Traigent framework.

Domain: customer_service
Difficulty: medium
Generated by: Traigent Problem Manager
"""

import random
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from examples.langchain_problems.base import (
    ProblemConfig,
    ProblemDefinition,
)
from . import register_problem


@dataclass
class CustomerSupportRequestClassificationConfig(ProblemConfig):
    """Configuration for customer_support_request_classification problem."""

    # Model configuration space
    model: str = "gpt-4o-mini"
    temperature: float = 0.3
    max_tokens: int = 50

    def get_config_space(self) -> Dict[str, List[Any]]:
        """Define the optimization search space."""
        return {
            "model": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
            "temperature": [
                0.1,
                0.16,
                0.22,
                0.28,
                0.34,
                0.4,
                0.46,
                0.52,
                0.58,
                0.64,
                0.7,
            ],
            "max_tokens": [self.max_tokens],
        }


class CustomerSupportRequestClassification(ProblemDefinition):
    """
    Automatically categorize incoming customer support requests into predefined categories such as technical issues, billing inquiries, product questions, complaints, feature requests, or account management to enable proper routing and prioritization

    Problem Type: classification
    Domain: customer_service
    Difficulty: medium
    Examples: 25
    """

    def __init__(
        self, config: Optional[CustomerSupportRequestClassificationConfig] = None
    ):
        """Initialize with optional config."""
        self.config = config or CustomerSupportRequestClassificationConfig()
        super().__init__(self.config)
        self.examples = self._load_examples()

    def _load_examples(self) -> List[Dict[str, Any]]:
        """Load the example dataset."""
        return [
            {
                "expected_output": "billing_issue",
                "id": 1,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "technical_support",
                "id": 2,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "order_inquiry",
                "id": 3,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "order_inquiry",
                "id": 4,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 5,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "technical_support",
                "id": 6,
                "input_data": {"text": "The product page won't load properly"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "order_inquiry",
                "id": 7,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 8,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "order_inquiry",
                "id": 9,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "order_inquiry",
                "id": 10,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "general_question",
                "id": 11,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 12,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 13,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "technical_support",
                "id": 14,
                "input_data": {"text": "The product page won't load properly"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "technical_support",
                "id": 15,
                "input_data": {"text": "The product page won't load properly"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "order_inquiry",
                "id": 16,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "technical_support",
                "id": 17,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 18,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "technical_support",
                "id": 19,
                "input_data": {"text": "The product page won't load properly"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 20,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 21,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "order_inquiry",
                "id": 22,
                "input_data": {"text": "Can I change my delivery address?"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 23,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "billing_issue",
                "id": 24,
                "input_data": {"text": "I was charged twice for my order"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
            {
                "expected_output": "technical_support",
                "id": 25,
                "input_data": {"text": "The product page won't load properly"},
                "metadata": {
                    "category": "customer_service",
                    "difficulty": "medium",
                    "domain": "customer_service",
                    "problem_type": "classification",
                    "reasoning": "Generated using ClassificationProblem constraints",
                },
            },
        ]

    def get_dataset(self) -> Any:
        """Return the dataset for this problem."""
        return self.examples

    def create_dataset(self, subset_size: Optional[int] = None) -> List[Dict[str, Any]]:
        """Create dataset for optimization."""
        dataset = self.examples.copy()

        if subset_size and subset_size < len(dataset):
            random.shuffle(dataset)
            dataset = dataset[:subset_size]

        return dataset

    def create_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create the base function to optimize."""

        def classify_customer_support_request_classification(
            input_data: Dict[str, Any],
            config: CustomerSupportRequestClassificationConfig,
        ) -> str:
            """
            Classify automatically categorize incoming customer support requests into predefined categories such as technical issues, billing inquiries, product questions, complaints, feature requests, or account management to enable proper routing and prioritization
            """
            from langchain.schema import HumanMessage
            from langchain_openai import ChatOpenAI

            # Initialize the model with current configuration
            llm = ChatOpenAI(
                model=config.model,
                temperature=config.temperature,
                model_kwargs={"max_tokens": config.max_tokens},
            )

            # Create prompt based on problem type
            # Classification prompt
            text = input_data.get("text", input_data.get("query", str(input_data)))

            prompt = f"""Classify the following text into one of these categories: "billing_issue", "technical_support", "product_inquiry", "shipping_inquiry", "return_request", "account_support"

Text: {text}

Category:"""

            # Get response
            response = llm.invoke([HumanMessage(content=prompt)])

            # Extract and format result
            # Extract classification result
            result = response.content.strip()
            # Clean up result to get just the category
            result = result.split("\n")[0].strip()

            return result

        return classify_customer_support_request_classification

    def create_optimized_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create optimized version using Traigent."""
        import traigent

        base_function = self.create_function(dataset)

        @traigent.optimize(
            config_class=CustomerSupportRequestClassificationConfig,
            dataset=dataset,
            metrics=[
                "f1_score",
                "precision",
                "confusion_matrix",
                "accuracy",
                "recall",
                "roc_auc",
            ],
        )
        def optimized_classify_customer_support_request_classification(
            input_data: Dict[str, Any],
            config: CustomerSupportRequestClassificationConfig,
        ) -> str:
            return base_function(input_data, config)

        return optimized_classify_customer_support_request_classification

    def evaluate_custom_metrics(self, results: List[Any]) -> Dict[str, float]:
        """Calculate custom evaluation metrics."""
        if not results:
            return {}

        metrics = {}

        # Basic metrics
        total_results = len(results)
        if total_results == 0:
            return {}

        successful_results = [r for r in results if r.success]
        success_rate = len(successful_results) / total_results
        metrics["success_rate"] = success_rate

        # Classification-specific metrics
        correct_predictions = 0
        for result in successful_results:
            expected = result.expected_output
            actual = result.result
            if str(expected).strip().lower() == str(actual).strip().lower():
                correct_predictions += 1

        if successful_results:
            metrics["accuracy"] = correct_predictions / len(successful_results)
        else:
            metrics["accuracy"] = 0.0
        # Custom metric: f1_score
        metrics["f1_score"] = 0.0  # Implement custom calculation
        # Custom metric: precision
        metrics["precision"] = 0.0  # Implement custom calculation
        # Custom metric: confusion_matrix
        metrics["confusion_matrix"] = 0.0  # Implement custom calculation
        # Custom metric: accuracy
        metrics["accuracy"] = 0.0  # Implement custom calculation
        # Custom metric: recall
        metrics["recall"] = 0.0  # Implement custom calculation
        # Custom metric: roc_auc
        metrics["roc_auc"] = 0.0  # Implement custom calculation

        return metrics


# Example usage and testing
if __name__ == "__main__":
    problem = CustomerSupportRequestClassification()
    dataset = problem.create_dataset(subset_size=5)

    print(f"Problem: {problem.__class__.__name__}")
    print(f"Dataset size: {len(dataset)}")
    print(f"Sample example: {dataset[0] if dataset else 'No examples'}")

    # Test base function
    base_func = problem.create_function(dataset)
    if dataset:
        result = base_func(dataset[0], problem.config)
        print(f"Sample result: {result}")


# Register this problem
register_problem(
    "customer_support_request_classification", CustomerSupportRequestClassification
)
