"""
Generate challenging JavaScript coding puzzles that test problem-solving skills, algorithmic thinking, and language-specific features

This module implements a generation problem for LangChain optimization
using the TraiGent framework.

Domain: technical
Difficulty: medium
Generated by: TraiGent Problem Manager
"""

import random
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from examples.langchain_problems.base import (
    ProblemConfig,
    ProblemDefinition,
)
from . import register_problem


@dataclass
class JavascriptCodingPuzzlesConfig(ProblemConfig):
    """Configuration for javascript_coding_puzzles problem."""

    def __init__(self):
        """Initialize configuration with required parameters."""
        super().__init__(
            name="javascript_coding_puzzles",
            description="Generate challenging JavaScript coding puzzles that test problem-solving skills, algorithmic thinking, and language-specific features",
            difficulty_level="medium",
            dataset_size=5,
            model_configurations={
                "model": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
                "temperature": [
                    0.1,
                    0.16,
                    0.22,
                    0.28,
                    0.34,
                    0.4,
                    0.46,
                    0.52,
                    0.58,
                    0.64,
                    0.7,
                ],
                "max_tokens": [600],
            },
            metrics=[
                {
                    "name": "relevance",
                    "description": "Measure relevance for generation problem",
                    "higher_is_better": True,
                    "weight": 1.0,
                },
                {
                    "name": "quality",
                    "description": "Measure quality for generation problem",
                    "higher_is_better": True,
                    "weight": 1.0,
                },
                {
                    "name": "accuracy",
                    "description": "Measure accuracy for generation problem",
                    "higher_is_better": True,
                    "weight": 1.0,
                },
            ],
            optimization_objectives=["relevance", "quality"],
        )

        # Set default model configuration
        self.model = "gpt-4o-mini"
        self.temperature = 0.3
        self.max_tokens = 600

    def get_config_space(self) -> Dict[str, List[Any]]:
        """Define the optimization search space."""
        return self.model_configurations


class JavascriptCodingPuzzles(ProblemDefinition):
    """
    Generate challenging JavaScript coding puzzles that test problem-solving skills, algorithmic thinking, and language-specific features

    Problem Type: generation
    Domain: technical
    Difficulty: medium
    Examples: 5
    """

    def __init__(self, config: Optional[JavascriptCodingPuzzlesConfig] = None):
        """Initialize with optional config."""
        self.config = config or JavascriptCodingPuzzlesConfig()
        super().__init__(self.config)
        self.examples = self._load_examples()

    def _load_examples(self) -> List[Dict[str, Any]]:
        """Load the example dataset."""
        return [
            {
                "expected_output": "Create a function that implements a custom Promise.all() without using the built-in "
                "method. Your implementation should handle an array of promises, resolve when all promises "
                "succeed with an array of results in order, and reject immediately if any promise fails. "
                "Consider edge cases like empty arrays and non-promise values. This puzzle tests "
                "understanding of promises, async behavior, and array manipulation while requiring careful "
                "attention to JavaScript's event loop and error handling patterns.",
                "id": 1,
                "input_data": {
                    "text": "Generate challenging JavaScript coding puzzles that test problem-solving skills, "
                    "algorithmic thinking, and language-specific features"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate challenging JavaScript coding puzzles that "
                    "test problem-solving skills, algorithmic thinking, and "
                    "language-specific features",
                    "pattern": "example_1",
                    "reasoning": "Example for generation task",
                },
            },
            {
                "expected_output": "Create a function that implements a custom Promise.all() without using the built-in "
                "method. Your implementation should handle an array of promises, resolve when all promises "
                "complete successfully, and reject immediately if any promise fails. Consider edge cases "
                "like empty arrays and non-promise values. This puzzle tests understanding of Promise "
                "mechanics, async behavior, and error handling in JavaScript's event loop.",
                "id": 2,
                "input_data": {
                    "text": "Generate challenging JavaScript coding puzzles that test problem-solving skills, "
                    "algorithmic thinking, and language-specific features"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate challenging JavaScript coding puzzles that "
                    "test problem-solving skills, algorithmic thinking, and "
                    "language-specific features",
                    "pattern": "example_2",
                    "reasoning": "Example for generation task",
                },
            },
            {
                "expected_output": "Write a debounce function that supports immediate execution and cancellation. The function "
                "should accept a callback, delay, and immediate flag. If immediate is true, execute on the "
                "leading edge. Include a cancel method to clear pending executions. This challenge explores "
                "closures, setTimeout management, and the this binding problem in JavaScript, requiring "
                "deep understanding of execution context.",
                "id": 3,
                "input_data": {
                    "text": "Generate challenging JavaScript coding puzzles that test problem-solving skills, "
                    "algorithmic thinking, and language-specific features"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate challenging JavaScript coding puzzles that "
                    "test problem-solving skills, algorithmic thinking, and "
                    "language-specific features",
                    "pattern": "example_3",
                    "reasoning": "Example for generation task",
                },
            },
            {
                "expected_output": "Stay hydrated in style with our eco-friendly reusable water bottle. Made from durable "
                "stainless steel, this 24oz bottle keeps drinks cold for 24 hours or hot for 12. The "
                "leak-proof design and wide mouth make it perfect for any adventure, while the sleek design "
                "fits in most cup holders. Available in multiple colors to match your personal style.",
                "id": 4,
                "input_data": {
                    "text": "Write a brief product description for a reusable water bottle"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Template-based example for Generate challenging JavaScript coding "
                    "puzzles that test problem-solving skills, algorithmic thinking, and "
                    "language-specific features",
                    "is_fallback": True,
                    "pattern": "fallback_generation_1",
                    "reasoning": "High-quality fallback example for generation",
                    "template_quality": "high",
                },
            },
            {
                "expected_output": "Welcome to our platform! We're excited to have you join our community. To get started, "
                "take a moment to complete your profile and explore our features. If you need any help "
                "along the way, our support team is here to assist you. Let's begin your journey!",
                "id": 5,
                "input_data": {"text": "Create a welcome message for new users"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "easy",
                    "domain_specific_info": "Template-based example for Generate challenging JavaScript coding "
                    "puzzles that test problem-solving skills, algorithmic thinking, and "
                    "language-specific features",
                    "is_fallback": True,
                    "pattern": "fallback_generation_2",
                    "reasoning": "High-quality fallback example for generation",
                    "template_quality": "high",
                },
            },
        ]

    def get_dataset(self) -> Any:
        """Return the dataset for this problem."""
        return self.examples

    def create_dataset(self, subset_size: Optional[int] = None) -> List[Dict[str, Any]]:
        """Create dataset for optimization."""
        dataset = self.examples.copy()

        if subset_size and subset_size < len(dataset):
            random.shuffle(dataset)
            dataset = dataset[:subset_size]

        return dataset

    def create_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create the base function to optimize."""

        def generate_javascript_coding_puzzles(
            input_data: Dict[str, Any], config: JavascriptCodingPuzzlesConfig
        ) -> str:
            """
            Generate generate challenging javascript coding puzzles that test problem-solving skills, algorithmic thinking, and language-specific features
            """
            from langchain.schema import HumanMessage
            from langchain_openai import ChatOpenAI

            # Initialize the model with current configuration
            llm = ChatOpenAI(
                model=config.model,
                temperature=config.temperature,
                model_kwargs={"max_tokens": config.max_tokens},
            )

            # Create prompt based on problem type
            # Generation prompt
            prompt_text = input_data.get(
                "prompt", input_data.get("text", str(input_data))
            )
            context = input_data.get("context", "")

            prompt = f"""Generate content based on the following prompt:

Prompt: {prompt_text}
{f"Context: {context}" if context else ""}

Generated content:"""

            # Get response
            response = llm.invoke([HumanMessage(content=prompt)])

            # Extract and format result
            # Extract text result
            result = response.content.strip()

            return result

        return generate_javascript_coding_puzzles

    def create_optimized_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create optimized version using TraiGent."""
        import traigent

        base_function = self.create_function(dataset)

        @traigent.optimize(
            config_class=JavascriptCodingPuzzlesConfig,
            dataset=dataset,
            metrics=["relevance", "quality", "accuracy"],
        )
        def optimized_generate_javascript_coding_puzzles(
            input_data: Dict[str, Any], config: JavascriptCodingPuzzlesConfig
        ) -> str:
            return base_function(input_data, config)

        return optimized_generate_javascript_coding_puzzles

    def evaluate_custom_metrics(self, results: List[Any]) -> Dict[str, float]:
        """Calculate custom evaluation metrics."""
        if not results:
            return {}

        metrics = {}

        # Basic metrics
        total_results = len(results)
        if total_results == 0:
            return {}

        successful_results = [r for r in results if r.success]
        success_rate = len(successful_results) / total_results
        metrics["success_rate"] = success_rate

        # Generation-specific metrics
        avg_length = 0
        if successful_results:
            total_length = sum(len(str(r.result)) for r in successful_results)
            avg_length = total_length / len(successful_results)
        metrics["avg_generation_length"] = avg_length
        # Custom metric: relevance
        metrics["relevance"] = 0.0  # Implement custom calculation
        # Custom metric: quality
        metrics["quality"] = 0.0  # Implement custom calculation
        # Custom metric: accuracy
        metrics["accuracy"] = 0.0  # Implement custom calculation

        return metrics


# Example usage and testing
if __name__ == "__main__":
    problem = JavascriptCodingPuzzles()
    dataset = problem.create_dataset(subset_size=5)

    print(f"Problem: {problem.__class__.__name__}")
    print(f"Dataset size: {len(dataset)}")
    print(f"Sample example: {dataset[0] if dataset else 'No examples'}")

    # Test base function
    base_func = problem.create_function(dataset)
    if dataset:
        result = base_func(dataset[0], problem.config)
        print(f"Sample result: {result}")


# Register this problem
register_problem("javascript_coding_puzzles", JavascriptCodingPuzzles)
