"""
Generate and answer medical questions covering symptoms, diagnoses, treatments, and general healthcare knowledge for educational and informational purposes

This module implements a question_answering problem for LangChain optimization
using the TraiGent framework.

Domain: medical
Difficulty: medium
Generated by: TraiGent Problem Manager
"""

import random
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from examples.langchain_problems.base import (
    ProblemConfig,
    ProblemDefinition,
)
from . import register_problem


@dataclass
class MedicalDiagnosticQuestionsConfig(ProblemConfig):
    """Configuration for medical_diagnostic_questions problem."""

    # Model configuration space
    model: str = "gpt-4o-mini"
    temperature: float = 0.3
    max_tokens: int = 260

    def get_config_space(self) -> Dict[str, List[Any]]:
        """Define the optimization search space."""
        return {
            "model": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
            "temperature": [
                0.1,
                0.16,
                0.22,
                0.28,
                0.34,
                0.4,
                0.46,
                0.52,
                0.58,
                0.64,
                0.7,
            ],
            "max_tokens": [self.max_tokens],
        }


class MedicalDiagnosticQuestions(ProblemDefinition):
    """
    Generate and answer medical questions covering symptoms, diagnoses, treatments, and general healthcare knowledge for educational and informational purposes

    Problem Type: question_answering
    Domain: medical
    Difficulty: medium
    Examples: 25
    """

    def __init__(self, config: Optional[MedicalDiagnosticQuestionsConfig] = None):
        """Initialize with optional config."""
        self.config = config or MedicalDiagnosticQuestionsConfig()
        super().__init__(self.config)
        self.examples = self._load_examples()

    def _load_examples(self) -> List[Dict[str, Any]]:
        """Load the example dataset."""
        return [
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 1,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 2,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 3,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 4,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 5,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 6,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 7,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 8,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 9,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 10,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 11,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 12,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 13,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 14,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 15,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 16,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 17,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 18,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 19,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 20,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 21,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 22,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 23,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 24,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
            {
                "expected_output": "The key concepts involve understanding the fundamental aspects of Generate and answer "
                "medical questions covering symptoms, diagnoses, treatments, and general healthcare "
                "knowledge for educational and informational purposes in the medical field.",
                "id": 25,
                "input_data": {
                    "context": "This relates to medical domain concepts.",
                    "question": "Explain the key concepts related to: Generate and answer medical questions "
                    "covering symptoms, diagnoses, treatments, and general healthcare knowledge for "
                    "educational and informational purposes",
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain": "medical",
                    "has_context": True,
                    "problem_type": "question_answering",
                    "qa_type": "open",
                    "reasoning": "Generated using QuestionAnsweringProblem constraints",
                },
            },
        ]

    def get_dataset(self) -> Any:
        """Return the dataset for this problem."""
        return self.examples

    def create_dataset(self, subset_size: Optional[int] = None) -> List[Dict[str, Any]]:
        """Create dataset for optimization."""
        dataset = self.examples.copy()

        if subset_size and subset_size < len(dataset):
            random.shuffle(dataset)
            dataset = dataset[:subset_size]

        return dataset

    def create_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create the base function to optimize."""

        def process_medical_diagnostic_questions(
            input_data: Dict[str, Any], config: MedicalDiagnosticQuestionsConfig
        ) -> str:
            """
            Process generate and answer medical questions covering symptoms, diagnoses, treatments, and general healthcare knowledge for educational and informational purposes
            """
            from langchain.schema import HumanMessage
            from langchain_openai import ChatOpenAI

            # Initialize the model with current configuration
            llm = ChatOpenAI(
                model=config.model,
                temperature=config.temperature,
                model_kwargs={"max_tokens": config.max_tokens},
            )

            # Create prompt based on problem type
            # Default prompt
            text = str(input_data)
            prompt = f"Process the following input: {text}"

            # Get response
            response = llm.invoke([HumanMessage(content=prompt)])

            # Extract and format result
            # Extract text result
            result = response.content.strip()

            return result

        return process_medical_diagnostic_questions

    def create_optimized_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create optimized version using TraiGent."""
        import traigent

        base_function = self.create_function(dataset)

        @traigent.optimize(
            config_class=MedicalDiagnosticQuestionsConfig,
            dataset=dataset,
            metrics=[
                "exact_match",
                "factual_accuracy",
                "f1_score",
                "answer_relevance",
                "answer_accuracy",
            ],
        )
        def optimized_process_medical_diagnostic_questions(
            input_data: Dict[str, Any], config: MedicalDiagnosticQuestionsConfig
        ) -> str:
            return base_function(input_data, config)

        return optimized_process_medical_diagnostic_questions

    def evaluate_custom_metrics(self, results: List[Any]) -> Dict[str, float]:
        """Calculate custom evaluation metrics."""
        if not results:
            return {}

        metrics = {}

        # Basic metrics
        total_results = len(results)
        if total_results == 0:
            return {}

        successful_results = [r for r in results if r.success]
        success_rate = len(successful_results) / total_results
        metrics["success_rate"] = success_rate
        # Custom metric: exact_match
        metrics["exact_match"] = 0.0  # Implement custom calculation
        # Custom metric: factual_accuracy
        metrics["factual_accuracy"] = 0.0  # Implement custom calculation
        # Custom metric: f1_score
        metrics["f1_score"] = 0.0  # Implement custom calculation
        # Custom metric: answer_relevance
        metrics["answer_relevance"] = 0.0  # Implement custom calculation
        # Custom metric: answer_accuracy
        metrics["answer_accuracy"] = 0.0  # Implement custom calculation

        return metrics


# Example usage and testing
if __name__ == "__main__":
    problem = MedicalDiagnosticQuestions()
    dataset = problem.create_dataset(subset_size=5)

    print(f"Problem: {problem.__class__.__name__}")
    print(f"Dataset size: {len(dataset)}")
    print(f"Sample example: {dataset[0] if dataset else 'No examples'}")

    # Test base function
    base_func = problem.create_function(dataset)
    if dataset:
        result = base_func(dataset[0], problem.config)
        print(f"Sample result: {result}")


# Register this problem
register_problem("medical_diagnostic_questions", MedicalDiagnosticQuestions)
