"""
Generate SQL queries from natural language text descriptions, converting user requests into syntactically correct and semantically accurate SQL statements

This module implements a code_generation problem for LangChain optimization
using the TraiGent framework.

Domain: technical
Difficulty: medium
Generated by: TraiGent Problem Manager
"""

import random
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from examples.langchain_problems.base import (
    ProblemConfig,
    ProblemDefinition,
)
from . import register_problem


@dataclass
class TextToSqlQueryGenerationConfig(ProblemConfig):
    """Configuration for text_to_sql_query_generation problem."""

    # Model configuration space
    model: str = "gpt-4o-mini"
    temperature: float = 0.3
    max_tokens: int = 240

    def get_config_space(self) -> Dict[str, List[Any]]:
        """Define the optimization search space."""
        return {
            "model": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
            "temperature": [
                0.1,
                0.16,
                0.22,
                0.28,
                0.34,
                0.4,
                0.46,
                0.52,
                0.58,
                0.64,
                0.7,
            ],
            "max_tokens": [self.max_tokens],
        }


class TextToSqlQueryGeneration(ProblemDefinition):
    """
    Generate SQL queries from natural language text descriptions, converting user requests into syntactically correct and semantically accurate SQL statements

    Problem Type: code_generation
    Domain: technical
    Difficulty: medium
    Examples: 25
    """

    def __init__(self, config: Optional[TextToSqlQueryGenerationConfig] = None):
        """Initialize with optional config."""
        self.config = config or TextToSqlQueryGenerationConfig()
        super().__init__(self.config)
        self.examples = self._load_examples()

    def _load_examples(self) -> List[Dict[str, Any]]:
        """Load the example dataset."""
        return [
            {
                "expected_output": "To be determined",
                "id": 1,
                "input_data": {
                    "text": "I'll generate 25 diverse examples for converting natural language to SQL queries, "
                    "covering various database operations, complexity levels, and common use cases."
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_1",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 2,
                "input_data": {"text": "```json"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_2",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 3,
                "input_data": {"text": "["},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_3",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 4,
                "input_data": {"text": "{"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_4",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 5,
                "input_data": {
                    "text": '"input": "Show me all customers from New York",'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_5",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 6,
                "input_data": {
                    "text": '"output": "SELECT * FROM customers WHERE city = \'New York\';"'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_6",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 7,
                "input_data": {"text": "},"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_7",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 8,
                "input_data": {"text": "{"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_8",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 9,
                "input_data": {
                    "text": '"input": "Count the total number of orders placed in 2023",'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_9",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 10,
                "input_data": {
                    "text": '"output": "SELECT COUNT(*) FROM orders WHERE YEAR(order_date) = 2023;"'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_10",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 11,
                "input_data": {"text": "},"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_11",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 12,
                "input_data": {"text": "{"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_12",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 13,
                "input_data": {
                    "text": '"input": "Find the top 5 best-selling products by quantity sold",'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_13",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 14,
                "input_data": {
                    "text": '"output": "SELECT product_name, SUM(quantity) as total_sold FROM order_items oi '
                    "JOIN products p ON oi.product_id = p.product_id GROUP BY product_name ORDER BY "
                    'total_sold DESC LIMIT 5;"'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_14",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 15,
                "input_data": {"text": "},"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_15",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 16,
                "input_data": {"text": "{"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_16",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 17,
                "input_data": {
                    "text": '"input": "Get all employees who earn more than 50000 and work in the sales '
                    'department",'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_17",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 18,
                "input_data": {
                    "text": '"output": "SELECT * FROM employees WHERE salary > 50000 AND department = \'sales\';"'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_18",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 19,
                "input_data": {"text": "},"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_19",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 20,
                "input_data": {"text": "{"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_20",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 21,
                "input_data": {
                    "text": '"input": "Update the price of product with ID 123 to 29.99",'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_21",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 22,
                "input_data": {
                    "text": '"output": "UPDATE products SET price = 29.99 WHERE product_id = 123;"'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_22",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 23,
                "input_data": {"text": "},"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_23",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 24,
                "input_data": {"text": "{"},
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_24",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
            {
                "expected_output": "To be determined",
                "id": 25,
                "input_data": {
                    "text": '"input": "Delete all orders that were cancelled",'
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Generate SQL queries from natural language text "
                    "descriptions, converting user requests into syntactically correct and "
                    "semantically accurate SQL statements",
                    "pattern": "example_25",
                    "reasoning": "Fallback example for code_generation task",
                },
            },
        ]

    def get_dataset(self) -> Any:
        """Return the dataset for this problem."""
        return self.examples

    def create_dataset(self, subset_size: Optional[int] = None) -> List[Dict[str, Any]]:
        """Create dataset for optimization."""
        dataset = self.examples.copy()

        if subset_size and subset_size < len(dataset):
            random.shuffle(dataset)
            dataset = dataset[:subset_size]

        return dataset

    def create_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create the base function to optimize."""

        def process_text_to_sql_query_generation(
            input_data: Dict[str, Any], config: TextToSqlQueryGenerationConfig
        ) -> str:
            """
            Process generate sql queries from natural language text descriptions, converting user requests into syntactically correct and semantically accurate sql statements
            """
            from langchain.schema import HumanMessage
            from langchain_openai import ChatOpenAI

            # Initialize the model with current configuration
            llm = ChatOpenAI(
                model=config.model,
                temperature=config.temperature,
                model_kwargs={"max_tokens": config.max_tokens},
            )

            # Create prompt based on problem type
            # Default prompt
            text = str(input_data)
            prompt = f"Process the following input: {text}"

            # Get response
            response = llm.invoke([HumanMessage(content=prompt)])

            # Extract and format result
            # Extract text result
            result = response.content.strip()

            return result

        return process_text_to_sql_query_generation

    def create_optimized_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create optimized version using TraiGent."""
        import traigent

        base_function = self.create_function(dataset)

        @traigent.optimize(
            config_class=TextToSqlQueryGenerationConfig,
            dataset=dataset,
            metrics=[
                "semantic_similarity",
                "execution_match",
                "functional_correctness",
                "exact_match",
                "syntax_validity",
            ],
        )
        def optimized_process_text_to_sql_query_generation(
            input_data: Dict[str, Any], config: TextToSqlQueryGenerationConfig
        ) -> str:
            return base_function(input_data, config)

        return optimized_process_text_to_sql_query_generation

    def evaluate_custom_metrics(self, results: List[Any]) -> Dict[str, float]:
        """Calculate custom evaluation metrics."""
        if not results:
            return {}

        metrics = {}

        # Basic metrics
        total_results = len(results)
        if total_results == 0:
            return {}

        successful_results = [r for r in results if r.success]
        success_rate = len(successful_results) / total_results
        metrics["success_rate"] = success_rate
        # Custom metric: semantic_similarity
        metrics["semantic_similarity"] = 0.0  # Implement custom calculation
        # Custom metric: execution_match
        metrics["execution_match"] = 0.0  # Implement custom calculation
        # Custom metric: functional_correctness
        metrics["functional_correctness"] = 0.0  # Implement custom calculation
        # Custom metric: exact_match
        metrics["exact_match"] = 0.0  # Implement custom calculation
        # Custom metric: syntax_validity
        metrics["syntax_validity"] = 0.0  # Implement custom calculation

        return metrics


# Example usage and testing
if __name__ == "__main__":
    problem = TextToSqlQueryGeneration()
    dataset = problem.create_dataset(subset_size=5)

    print(f"Problem: {problem.__class__.__name__}")
    print(f"Dataset size: {len(dataset)}")
    print(f"Sample example: {dataset[0] if dataset else 'No examples'}")

    # Test base function
    base_func = problem.create_function(dataset)
    if dataset:
        result = base_func(dataset[0], problem.config)
        print(f"Sample result: {result}")


# Register this problem
register_problem("text_to_sql_query_generation", TextToSqlQueryGeneration)
