"""Type definitions for __traigent_meta__ structure.

This module provides TypedDict definitions and type guards for the reserved
`__traigent_meta__` key used by multi-agent workflows to report costs and
token usage to Traigent.

Example usage:
    from traigent.core.meta_types import is_traigent_metadata

    meta = output.get("__traigent_meta__")
    if is_traigent_metadata(meta):
        # Type checker knows meta has correct structure
        cost = meta["total_cost"]
        if "usage" in meta:
            tokens = meta["usage"]["input_tokens"]
"""

# Traceability: CONC-Layer-Core CONC-Quality-Reliability FUNC-EVAL-METRICS REQ-EVAL-005

from typing import Any, TypedDict, TypeGuard

try:
    from typing import NotRequired  # Python 3.11+
except ImportError:
    from typing import NotRequired  # Python 3.8-3.10


class UsageMetadata(TypedDict):
    """Token usage metadata within __traigent_meta__.

    Attributes:
        input_tokens: Number of input tokens consumed
        output_tokens: Number of output tokens generated
        response_time_ms: Response time in milliseconds (optional)
    """

    input_tokens: int
    output_tokens: int
    response_time_ms: NotRequired[float]


class CallCostEntry(TypedDict):
    """One LLM call's token/cost attribution within a multi-model trial.

    Multi-step / cascade / router agents call more than one model per
    trial (e.g. a cheap model decomposes a query and a strong model
    generates the answer). Without per-call attribution, downstream cost
    analysis only sees a single blended ``total_cost`` and has to guess
    which model actually spent it (Traigent#1598).

    Attributes:
        model: Model identifier the call was made against (e.g. "gpt-4o-mini").
        input_tokens: Input tokens consumed by this specific call.
        output_tokens: Output tokens generated by this specific call.
        cost: Cost in USD attributable to this specific call.
    """

    model: str
    input_tokens: int
    output_tokens: int
    cost: float


class TraigentMetadata(TypedDict):
    """Structure of __traigent_meta__ dict injected by with_usage().

    This is the canonical structure for reporting multi-agent workflow
    costs and token usage to Traigent's optimization engine.

    Attributes:
        total_cost: Total cost in USD for the operation
        usage: Optional token usage breakdown
        calls: Optional per-call/per-model cost breakdown for multi-model
            and multi-step agents (Traigent#1598). Each entry attributes
            tokens/cost to the model that made that specific call, so
            multi-model pipelines (per-step model selection, routing) get
            accurate, attributable cost instead of a single blended total.
    """

    total_cost: float
    usage: NotRequired[UsageMetadata]
    calls: NotRequired[list[CallCostEntry]]


def is_traigent_metadata(obj: Any) -> TypeGuard[TraigentMetadata]:
    """Type guard for runtime validation of __traigent_meta__ structure.

    Validates that an object conforms to the TraigentMetadata structure:
    - Must be a dict
    - Must have "total_cost" key with numeric value
    - If "usage" key present, must be dict with integer token counts

    Args:
        obj: Object to validate

    Returns:
        True if obj is a valid TraigentMetadata dict, False otherwise

    Example:
        >>> meta = {"total_cost": 0.001, "usage": {"input_tokens": 100, "output_tokens": 50}}
        >>> if is_traigent_metadata(meta):
        ...     cost = meta["total_cost"]  # Type checker knows this is safe
    """
    if not isinstance(obj, dict):
        return False

    # Required field: total_cost must be numeric
    if "total_cost" not in obj:
        return False
    if not isinstance(obj["total_cost"], (int, float)):
        return False

    # Optional field: usage must have correct structure if present
    if "usage" in obj:
        usage = obj["usage"]
        if not isinstance(usage, dict):
            return False

        # Validate token fields if present
        if "input_tokens" in usage:
            if not isinstance(usage["input_tokens"], int):
                return False
        if "output_tokens" in usage:
            if not isinstance(usage["output_tokens"], int):
                return False
        # Validate response_time_ms if present (optional, float)
        if "response_time_ms" in usage:
            if not isinstance(usage["response_time_ms"], (int, float)):
                return False

    # Optional field: calls must be a list of per-call breakdown dicts
    if "calls" in obj:
        calls = obj["calls"]
        if not isinstance(calls, list):
            return False
        for call in calls:
            if not isinstance(call, dict):
                return False
            if "model" not in call or not isinstance(call["model"], str):
                return False
            if "cost" not in call or isinstance(call["cost"], bool):
                return False
            if not isinstance(call["cost"], (int, float)):
                return False
            for token_key in ("input_tokens", "output_tokens"):
                if token_key in call and (
                    isinstance(call[token_key], bool)
                    or not isinstance(call[token_key], int)
                ):
                    return False

    return True
