"""Public observability API for Traigent SDK."""

from traigent.observability.agent_spans import add_agent_span
from traigent.observability.client import ObservabilityClient
from traigent.observability.config import ObservabilityConfig
from traigent.observability.decorators import (
    ObserveContext,
    get_default_observability_client,
    observe,
    set_default_observability_client,
)
from traigent.observability.dtos import (
    CorrelationIds,
    FlushResult,
    ObservationDTO,
    ObservationRecord,
    ObservationType,
    PaginationInfo,
    PromptLinkRecord,
    PromptReferenceDTO,
    SessionDTO,
    SessionListResponse,
    SessionRecord,
    ThumbRating,
    TraceCollaborationState,
    TraceCommentRecord,
    TraceCommentsResponse,
    TraceDTO,
    TraceFeedbackRecord,
    TraceFeedbackResponse,
    TraceFeedbackSummary,
    TraceListResponse,
    TraceObservationsResponse,
    TraceRecord,
)

__all__ = [
    "CorrelationIds",
    "FlushResult",
    "ObservationDTO",
    "ObservationRecord",
    "ObservationType",
    "ObserveContext",
    "ObservabilityClient",
    "ObservabilityConfig",
    "PaginationInfo",
    "PromptLinkRecord",
    "PromptReferenceDTO",
    "SessionListResponse",
    "SessionRecord",
    "SessionDTO",
    "ThumbRating",
    "TraceCollaborationState",
    "TraceCommentRecord",
    "TraceCommentsResponse",
    "TraceDTO",
    "TraceFeedbackRecord",
    "TraceFeedbackResponse",
    "TraceFeedbackSummary",
    "TraceListResponse",
    "TraceObservationsResponse",
    "TraceRecord",
    "add_agent_span",
    "get_default_observability_client",
    "observe",
    "set_default_observability_client",
]
