"""
An educational assistant that helps students learn American history by answering questions about historical events, figures, documents, and periods from pre-colonial times through the present day

This module implements a question_answering problem for LangChain optimization
using the Traigent framework.

Domain: educational
Difficulty: medium
Generated by: Traigent Problem Manager
"""

import sys
from typing import Any, Callable, Dict, List, Optional

import traigent
from traigent.evaluators.base import Dataset, EvaluationExample

try:
    from langchain.chains import LLMChain
    from langchain.prompts import ChatPromptTemplate
    from langchain_openai import ChatOpenAI
except ImportError:
    print("Please install LangChain: pip install langchain langchain-openai")
    sys.exit(1)

from . import register_problem
from .base import BaseLangChainProblem, ProblemConfig, ProblemMetric


class AmericanHistoryQaTutor(BaseLangChainProblem):
    """
    An educational assistant that helps students learn American history by answering questions about historical events, figures, documents, and periods from pre-colonial times through the present day

    Problem Type: question_answering
    Domain: educational
    Difficulty: medium
    Examples: 3
    """

    @classmethod
    def get_default_config(cls) -> ProblemConfig:
        """Get default configuration for this problem."""
        return ProblemConfig(
            name="american_history_qa_tutor",
            description="Educational assistant for American history Q&A from pre-colonial times through present day",
            difficulty_level="Medium",
            dataset_size=30,
            model_configurations={
                "model": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
                "temperature": [0.1, 0.3, 0.5, 0.7],
                "max_tokens": [200, 300],
            },
            metrics=[
                ProblemMetric(
                    "accuracy", "Answer accuracy and completeness", True, 1.0, ".1%"
                ),
                ProblemMetric(
                    "relevance", "Relevance to the question asked", True, 0.9, ".1%"
                ),
                ProblemMetric(
                    "educational_value",
                    "Educational quality of response",
                    True,
                    0.8,
                    ".1%",
                ),
                ProblemMetric(
                    "factual_accuracy",
                    "Historical factual correctness",
                    True,
                    1.1,
                    ".1%",
                ),
            ],
            optimization_objectives=["accuracy"],
            expected_model_ranking=["gpt-4o", "gpt-4o-mini", "gpt-3.5-turbo"],
        )

    def __init__(self, config: Optional[ProblemConfig] = None):
        if config is None:
            config = self.get_default_config()
        super().__init__(config)

    def create_dataset(self) -> Dataset:
        """Create the evaluation dataset for American history Q&A."""
        examples_data = [
            # Easy questions
            {
                "question": "Who was the first president of the United States?",
                "expected_answer": "George Washington was the first president of the United States, serving from 1789 to 1797.",
                "difficulty": "easy",
                "topic": "Presidents",
            },
            {
                "question": "What year did Christopher Columbus first arrive in the Americas?",
                "expected_answer": "Christopher Columbus first arrived in the Americas in 1492.",
                "difficulty": "easy",
                "topic": "Exploration",
            },
            {
                "question": "What document declared American independence from Britain?",
                "expected_answer": "The Declaration of Independence, adopted on July 4, 1776, declared American independence from Britain.",
                "difficulty": "easy",
                "topic": "Founding Documents",
            },
            # Medium questions
            {
                "question": "What were the main causes of the American Civil War?",
                "expected_answer": "The main causes of the American Civil War included slavery, states' rights, economic differences between North and South, and the election of Abraham Lincoln in 1860.",
                "difficulty": "medium",
                "topic": "Civil War",
            },
            {
                "question": "Explain the significance of the Louisiana Purchase in 1803.",
                "expected_answer": "The Louisiana Purchase in 1803 doubled the size of the United States, acquiring approximately 828,000 square miles from France for $15 million. It secured control of the Mississippi River and the port of New Orleans, and enabled westward expansion.",
                "difficulty": "medium",
                "topic": "Territorial Expansion",
            },
            {
                "question": "Who were the key figures in drafting the Declaration of Independence?",
                "expected_answer": "The key figures in drafting the Declaration of Independence were Thomas Jefferson (primary author), John Adams, Benjamin Franklin, Roger Sherman, and Robert Livingston, who formed the Committee of Five.",
                "difficulty": "medium",
                "topic": "Founding Fathers",
            },
            # Hard questions
            {
                "question": "How did the Compromise of 1850 attempt to address slavery, and why did it ultimately fail?",
                "expected_answer": "The Compromise of 1850 included admitting California as a free state, creating Utah and New Mexico territories with popular sovereignty, settling the Texas boundary dispute, ending slave trade in D.C., and strengthening the Fugitive Slave Act. It failed because it didn't resolve the fundamental conflict over slavery's expansion and increased tensions through the controversial Fugitive Slave Act.",
                "difficulty": "hard",
                "topic": "Antebellum Period",
            },
            {
                "question": "Analyze the impact of the Great Depression on American society and Roosevelt's New Deal response.",
                "expected_answer": "The Great Depression (1929-1939) caused 25% unemployment, bank failures, and widespread poverty. Roosevelt's New Deal (1933-1939) created programs like Social Security, WPA, and CCC, fundamentally expanding federal government's role in economic and social welfare, establishing the modern welfare state and regulatory framework.",
                "difficulty": "hard",
                "topic": "20th Century",
            },
            # Additional examples to reach 30
            {
                "question": "What was the Boston Tea Party?",
                "expected_answer": "The Boston Tea Party (December 16, 1773) was a political protest where American colonists dumped 342 chests of British tea into Boston Harbor to protest the Tea Act and taxation without representation.",
                "difficulty": "easy",
                "topic": "Revolutionary Period",
            },
            {
                "question": "Who wrote the Constitution?",
                "expected_answer": "James Madison is known as the 'Father of the Constitution' for his pivotal role in drafting and promoting the U.S. Constitution and Bill of Rights.",
                "difficulty": "easy",
                "topic": "Founding Documents",
            },
        ]

        # Create more examples to reach 30
        additional_topics = [
            (
                "What was Manifest Destiny?",
                "Manifest Destiny was the 19th-century belief that American expansion across the continent was justified and inevitable, driving westward expansion and territorial acquisitions.",
                "medium",
                "Expansion",
            ),
            (
                "Describe the Trail of Tears.",
                "The Trail of Tears (1838-1839) was the forced removal of Cherokee and other Native American nations from their southeastern homelands to Indian Territory (Oklahoma), resulting in thousands of deaths.",
                "medium",
                "Native American History",
            ),
            (
                "What was the Monroe Doctrine?",
                "The Monroe Doctrine (1823) declared that European colonization in the Americas would be viewed as aggression requiring U.S. intervention, establishing America's sphere of influence in the Western Hemisphere.",
                "medium",
                "Foreign Policy",
            ),
            (
                "Explain the significance of Brown v. Board of Education.",
                "Brown v. Board of Education (1954) was a landmark Supreme Court case that declared racial segregation in public schools unconstitutional, overturning 'separate but equal' doctrine and catalyzing the Civil Rights Movement.",
                "hard",
                "Civil Rights",
            ),
            (
                "What was the Marshall Plan?",
                "The Marshall Plan (1948-1952) was an American initiative providing over $12 billion in economic assistance to rebuild Western European economies after World War II, containing Soviet influence.",
                "medium",
                "Cold War",
            ),
            (
                "Who were the Federalists and Anti-Federalists?",
                "Federalists supported ratifying the Constitution and strong federal government (Hamilton, Madison, Jay), while Anti-Federalists opposed it fearing tyranny and demanding a Bill of Rights (Henry, Mason).",
                "medium",
                "Early Republic",
            ),
            (
                "What was the Emancipation Proclamation?",
                "The Emancipation Proclamation (1863) was Lincoln's executive order freeing slaves in Confederate states, transforming the Civil War into a fight for freedom and preventing European intervention.",
                "medium",
                "Civil War",
            ),
            (
                "Describe the impact of the transcontinental railroad.",
                "The transcontinental railroad (completed 1869) connected east and west coasts, revolutionizing transportation, commerce, and settlement while devastating Native American communities and buffalo populations.",
                "hard",
                "Industrialization",
            ),
            (
                "What was the Watergate scandal?",
                "Watergate (1972-1974) was a political scandal involving Nixon administration's break-in at Democratic headquarters and subsequent cover-up, leading to Nixon's resignation and erosion of public trust.",
                "hard",
                "Modern Politics",
            ),
            (
                "Explain the significance of the Bill of Rights.",
                "The Bill of Rights (1791) comprises the first ten amendments to the Constitution, guaranteeing fundamental freedoms like speech, religion, and due process, addressing Anti-Federalist concerns.",
                "easy",
                "Constitutional Law",
            ),
        ]

        for q, a, d, t in additional_topics:
            examples_data.append(
                {"question": q, "expected_answer": a, "difficulty": d, "topic": t}
            )

        # Add remaining examples to reach 30
        final_examples = [
            (
                "What was the Cold War?",
                "The Cold War (1947-1991) was a period of geopolitical tension between the United States and Soviet Union, characterized by ideological conflict, proxy wars, arms race, and space race without direct military confrontation.",
                "medium",
                "Cold War",
            ),
            (
                "Who was Martin Luther King Jr.?",
                "Martin Luther King Jr. (1929-1968) was a Baptist minister and civil rights leader who advocated nonviolent resistance, delivering the 'I Have a Dream' speech and winning the Nobel Peace Prize.",
                "easy",
                "Civil Rights",
            ),
            (
                "What was the Industrial Revolution's impact on America?",
                "The Industrial Revolution (late 1800s-early 1900s) transformed America from agricultural to industrial economy, creating factories, urbanization, labor movements, wealth inequality, and technological innovation.",
                "hard",
                "Industrialization",
            ),
            (
                "Describe the Cuban Missile Crisis.",
                "The Cuban Missile Crisis (1962) was a 13-day confrontation between US and USSR over Soviet missiles in Cuba, bringing the world closest to nuclear war before diplomatic resolution.",
                "hard",
                "Cold War",
            ),
            (
                "What was Reconstruction?",
                "Reconstruction (1865-1877) was the period after the Civil War attempting to rebuild the South and integrate freed slaves, marked by constitutional amendments, political conflict, and ultimate failure to ensure racial equality.",
                "medium",
                "Post-Civil War",
            ),
            (
                "Who were Lewis and Clark?",
                "Meriwether Lewis and William Clark led the Corps of Discovery expedition (1804-1806) exploring the Louisiana Purchase territory, mapping routes to the Pacific and documenting Native American tribes.",
                "easy",
                "Exploration",
            ),
            (
                "What was the Space Race?",
                "The Space Race was Cold War competition between US and USSR for spaceflight supremacy, beginning with Sputnik (1957) and culminating in the Apollo 11 moon landing (1969).",
                "medium",
                "Cold War",
            ),
            (
                "Explain the Great Migration.",
                "The Great Migration (1916-1970) was the movement of 6 million African Americans from rural South to urban North and West, seeking economic opportunities and escaping Jim Crow laws.",
                "hard",
                "20th Century",
            ),
            (
                "What was the Vietnam War's impact on America?",
                "The Vietnam War (1955-1975) divided American society, sparked anti-war movements, ended the draft, created veteran health crises, and led to War Powers Resolution limiting presidential military authority.",
                "hard",
                "Modern Wars",
            ),
            (
                "Who was Eleanor Roosevelt?",
                "Eleanor Roosevelt (1884-1962) was First Lady, diplomat, and human rights activist who transformed the role of First Lady and chaired the UN commission drafting the Universal Declaration of Human Rights.",
                "medium",
                "Notable Figures",
            ),
        ]

        for q, a, d, t in final_examples:
            examples_data.append(
                {"question": q, "expected_answer": a, "difficulty": d, "topic": t}
            )

        # Convert to Dataset format
        examples = []
        for i, data in enumerate(examples_data[:30]):  # Ensure exactly 30 examples
            example = EvaluationExample(
                input_data={"question": data["question"]},
                expected_output=data["expected_answer"],
                metadata={
                    "difficulty": data["difficulty"],
                    "topic": data["topic"],
                    "example_id": f"history_{i + 1:03d}",
                },
            )
            examples.append(example)

        return Dataset(
            examples=examples,
            name="American History Q&A",
            description="Educational Q&A dataset covering American history from pre-colonial times to present",
        )

    def create_function(self) -> Callable:
        """Create the base function to optimize."""

        def american_history_tutor(question: str) -> str:
            """Answer questions about American history."""
            llm = ChatOpenAI(
                model="gpt-4o-mini",
                temperature=0.3,
                model_kwargs={"max_tokens": 200},
            )

            prompt_template = ChatPromptTemplate.from_messages(
                [
                    (
                        "system",
                        """You are an educational assistant helping students learn American history.
Provide clear, accurate, and concise answers to historical questions.
Focus on key facts, dates, and significance.
Your answers should be educational and appropriate for students.""",
                    ),
                    (
                        "human",
                        "Question: {question}\n\nProvide a clear and informative answer:",
                    ),
                ]
            )

            chain = LLMChain(llm=llm, prompt=prompt_template)
            result = chain.invoke({"question": question})["text"]

            return result.strip()

        return american_history_tutor

    def create_optimized_function(self) -> Callable:
        """Create the optimized American history tutor."""

        @traigent.optimize(
            eval_dataset=self.create_temporary_dataset_file(),
            objectives=self.get_optimization_objectives(),
            configuration_space=self.get_configuration_space(),
            auto_override_frameworks=True,
            framework_targets=["langchain_openai.ChatOpenAI"],
            execution_mode="edge_analytics",
        )
        def american_history_tutor_optimized(question: str) -> str:
            """Optimized American history Q&A assistant."""
            llm = ChatOpenAI(
                model="gpt-4o-mini",  # Will be overridden by Traigent
                temperature=0.3,  # Will be overridden by Traigent
                model_kwargs={"max_tokens": 200},  # Will be overridden by Traigent
            )

            prompt_template = ChatPromptTemplate.from_messages(
                [
                    (
                        "system",
                        """You are an educational assistant helping students learn American history.
Provide clear, accurate, and concise answers to historical questions.
Focus on key facts, dates, and significance.
Your answers should be educational and appropriate for students.""",
                    ),
                    (
                        "human",
                        "Question: {question}\n\nProvide a clear and informative answer:",
                    ),
                ]
            )

            chain = LLMChain(llm=llm, prompt=prompt_template)
            result = chain.invoke({"question": question})["text"]

            return result.strip()

        return american_history_tutor_optimized

    def evaluate_custom_metrics(
        self,
        outputs: List[Any],
        expected_outputs: List[Any],
        errors: List[Optional[str]],
    ) -> Dict[str, float]:
        """Compute American history Q&A specific metrics."""
        metrics = {}

        # Get dataset for metadata access
        dataset = self.get_dataset()

        # Standard accuracy (contains key facts)
        correct = 0
        total = 0
        relevant = 0
        educational = 0
        factually_accurate = 0

        for i, (output, expected, error) in enumerate(
            zip(outputs, expected_outputs, errors)
        ):
            if error is None and expected is not None and output:
                total += 1
                output_lower = str(output).lower()
                expected_lower = str(expected).lower()

                # Extract key facts from expected answer
                import re

                # Extract years, names, and key terms
                expected_years = re.findall(r"\b(1[0-9]{3}|20[0-9]{2})\b", expected)
                expected_names = re.findall(r"[A-Z][a-z]+ [A-Z][a-z]+", expected)

                # Check if output contains key facts
                facts_found = 0
                total_facts = len(expected_years) + len(expected_names)

                for year in expected_years:
                    if year in output:
                        facts_found += 1

                for name in expected_names:
                    if name.lower() in output_lower:
                        facts_found += 1

                if total_facts > 0:
                    accuracy_score = facts_found / total_facts
                    if accuracy_score >= 0.6:  # 60% of key facts
                        correct += 1

                # Relevance check
                if i < len(dataset.examples):
                    question_words = (
                        dataset.examples[i].input_data["question"].lower().split()
                    )
                    relevant_words = sum(
                        1
                        for word in question_words
                        if len(word) > 3 and word in output_lower
                    )
                    if relevant_words >= 2:
                        relevant += 1

                # Educational value (includes explanations)
                educational_keywords = [
                    "because",
                    "resulted",
                    "led to",
                    "caused",
                    "impact",
                    "significance",
                    "important",
                ]
                if any(keyword in output_lower for keyword in educational_keywords):
                    educational += 1

                # Factual accuracy (no contradictions)
                contradiction_phrases = ["not", "never", "didn't", "wasn't", "false"]
                has_contradiction = False
                for phrase in contradiction_phrases:
                    if phrase in output_lower and phrase not in expected_lower:
                        has_contradiction = True
                        break
                if not has_contradiction:
                    factually_accurate += 1

        metrics["accuracy"] = correct / total if total > 0 else 0.0
        metrics["relevance"] = relevant / total if total > 0 else 0.0
        metrics["educational_value"] = educational / total if total > 0 else 0.0
        metrics["factual_accuracy"] = factually_accurate / total if total > 0 else 0.0

        return metrics


# Register this problem
register_problem("american_history_qa_tutor", AmericanHistoryQaTutor)
