"""
Solve logic puzzles and challenges using assembly language instructions, requiring understanding of low-level operations, registers, and memory manipulation

This module implements a reasoning problem for LangChain optimization
using the Traigent framework.

Domain: technical
Difficulty: medium
Generated by: Traigent Problem Manager
"""

import random
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from examples.langchain_problems.base import (
    ProblemConfig,
    ProblemDefinition,
)
from . import register_problem


@dataclass
class AssemblyCodeLogicPuzzlesConfig(ProblemConfig):
    """Configuration for assembly_code_logic_puzzles problem."""

    # Model configuration space
    model: str = "gpt-4o-mini"
    temperature: float = 0.3
    max_tokens: int = 240

    def get_config_space(self) -> Dict[str, List[Any]]:
        """Define the optimization search space."""
        return {
            "model": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
            "temperature": [
                0.1,
                0.16,
                0.22,
                0.28,
                0.34,
                0.4,
                0.46,
                0.52,
                0.58,
                0.64,
                0.7,
            ],
            "max_tokens": [self.max_tokens],
        }


class AssemblyCodeLogicPuzzles(ProblemDefinition):
    """
    Solve logic puzzles and challenges using assembly language instructions, requiring understanding of low-level operations, registers, and memory manipulation

    Problem Type: reasoning
    Domain: technical
    Difficulty: medium
    Examples: 5
    """

    def __init__(self, config: Optional[AssemblyCodeLogicPuzzlesConfig] = None):
        """Initialize with optional config."""
        self.config = config or AssemblyCodeLogicPuzzlesConfig()
        super().__init__(self.config)
        self.examples = self._load_examples()

    def _load_examples(self) -> List[Dict[str, Any]]:
        """Load the example dataset."""
        return [
            {
                "expected_output": {
                    "answer": "The function returns value_1",
                    "explanation": "Basic function analysis",
                },
                "id": 1,
                "input_data": {
                    "text": "Debug this code: function test_1() { return value_1; }"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Minimal fallback example for Solve logic puzzles and challenges using "
                    "assembly language instructions, requiring understanding of low-level "
                    "operations, registers, and memory manipulation",
                    "is_fallback": True,
                    "pattern": "fallback_pattern_1",
                    "reasoning": "Reasoning example for technical problems",
                },
            },
            {
                "expected_output": {
                    "answer": "The function returns value_2",
                    "explanation": "Basic function analysis",
                },
                "id": 2,
                "input_data": {
                    "text": "Debug this code: function test_2() { return value_2; }"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Minimal fallback example for Solve logic puzzles and challenges using "
                    "assembly language instructions, requiring understanding of low-level "
                    "operations, registers, and memory manipulation",
                    "is_fallback": True,
                    "pattern": "fallback_pattern_2",
                    "reasoning": "Reasoning example for technical problems",
                },
            },
            {
                "expected_output": {
                    "answer": "The function returns value_3",
                    "explanation": "Basic function analysis",
                },
                "id": 3,
                "input_data": {
                    "text": "Debug this code: function test_3() { return value_3; }"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Minimal fallback example for Solve logic puzzles and challenges using "
                    "assembly language instructions, requiring understanding of low-level "
                    "operations, registers, and memory manipulation",
                    "is_fallback": True,
                    "pattern": "fallback_pattern_3",
                    "reasoning": "Reasoning example for technical problems",
                },
            },
            {
                "expected_output": {
                    "answer": "The function returns value_4",
                    "explanation": "Basic function analysis",
                },
                "id": 4,
                "input_data": {
                    "text": "Debug this code: function test_4() { return value_4; }"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Minimal fallback example for Solve logic puzzles and challenges using "
                    "assembly language instructions, requiring understanding of low-level "
                    "operations, registers, and memory manipulation",
                    "is_fallback": True,
                    "pattern": "fallback_pattern_4",
                    "reasoning": "Reasoning example for technical problems",
                },
            },
            {
                "expected_output": {
                    "answer": "The function returns value_5",
                    "explanation": "Basic function analysis",
                },
                "id": 5,
                "input_data": {
                    "text": "Debug this code: function test_5() { return value_5; }"
                },
                "metadata": {
                    "category": "technical",
                    "difficulty": "medium",
                    "domain_specific_info": "Minimal fallback example for Solve logic puzzles and challenges using "
                    "assembly language instructions, requiring understanding of low-level "
                    "operations, registers, and memory manipulation",
                    "is_fallback": True,
                    "pattern": "fallback_pattern_5",
                    "reasoning": "Reasoning example for technical problems",
                },
            },
        ]

    def get_dataset(self) -> Any:
        """Return the dataset for this problem."""
        return self.examples

    def create_dataset(self, subset_size: Optional[int] = None) -> List[Dict[str, Any]]:
        """Create dataset for optimization."""
        dataset = self.examples.copy()

        if subset_size and subset_size < len(dataset):
            random.shuffle(dataset)
            dataset = dataset[:subset_size]

        return dataset

    def create_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create the base function to optimize."""

        def process_assembly_code_logic_puzzles(
            input_data: Dict[str, Any], config: AssemblyCodeLogicPuzzlesConfig
        ) -> str:
            """
            Process solve logic puzzles and challenges using assembly language instructions, requiring understanding of low-level operations, registers, and memory manipulation
            """
            from langchain.schema import HumanMessage
            from langchain_openai import ChatOpenAI

            # Initialize the model with current configuration
            llm = ChatOpenAI(
                model=config.model,
                temperature=config.temperature,
                max_tokens=config.max_tokens,
            )

            # Create prompt based on problem type
            # Default prompt
            text = str(input_data)
            prompt = f"Process the following input: {text}"

            # Get response
            response = llm.invoke([HumanMessage(content=prompt)])

            # Extract and format result
            # Extract text result
            result = response.content.strip()

            return result

        return process_assembly_code_logic_puzzles

    def create_optimized_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create optimized version using Traigent."""
        import traigent

        base_function = self.create_function(dataset)

        @traigent.optimize(
            config_class=AssemblyCodeLogicPuzzlesConfig,
            dataset=dataset,
            metrics=["relevance", "accuracy", "quality"],
        )
        def optimized_process_assembly_code_logic_puzzles(
            input_data: Dict[str, Any], config: AssemblyCodeLogicPuzzlesConfig
        ) -> str:
            return base_function(input_data, config)

        return optimized_process_assembly_code_logic_puzzles

    def evaluate_custom_metrics(self, results: List[Any]) -> Dict[str, float]:
        """Calculate custom evaluation metrics."""
        if not results:
            return {}

        metrics = {}

        # Basic metrics
        total_results = len(results)
        if total_results == 0:
            return {}

        successful_results = [r for r in results if r.success]
        success_rate = len(successful_results) / total_results
        metrics["success_rate"] = success_rate
        # Custom metric: relevance
        metrics["relevance"] = 0.0  # Implement custom calculation
        # Custom metric: accuracy
        metrics["accuracy"] = 0.0  # Implement custom calculation
        # Custom metric: quality
        metrics["quality"] = 0.0  # Implement custom calculation

        return metrics


# Example usage and testing
if __name__ == "__main__":
    problem = AssemblyCodeLogicPuzzles()
    dataset = problem.create_dataset(subset_size=5)

    print(f"Problem: {problem.__class__.__name__}")
    print(f"Dataset size: {len(dataset)}")
    print(f"Sample example: {dataset[0] if dataset else 'No examples'}")

    # Test base function
    base_func = problem.create_function(dataset)
    if dataset:
        result = base_func(dataset[0], problem.config)
        print(f"Sample result: {result}")


# Register this problem
register_problem("assembly_code_logic_puzzles", AssemblyCodeLogicPuzzles)
