"""
basic arithmetic

This module implements a classification problem for LangChain optimization
using the Traigent framework.

Domain: educational
Difficulty: Advanced
Generated by: Traigent Problem Manager
"""

import sys
from typing import Any, Callable, Dict, List, Optional

import traigent
from traigent.evaluators.base import Dataset, EvaluationExample

try:
    from langchain.chains import LLMChain
    from langchain.prompts import ChatPromptTemplate
    from langchain_openai import ChatOpenAI
except ImportError:
    print("Please install LangChain: pip install langchain langchain-openai")
    sys.exit(1)

from . import register_problem
from .base import BaseLangChainProblem, ProblemConfig, ProblemMetric


class BasicArithmeticProblem(BaseLangChainProblem):
    """
    basic arithmetic

    Problem Type: classification
    Domain: educational
    Difficulty: Advanced
    Examples: 20
    """

    @classmethod
    def get_default_config(cls) -> ProblemConfig:
        """Get default configuration for this problem."""
        return ProblemConfig(
            name="basic_arithmetic",
            description="Solve basic arithmetic problems including addition, subtraction, multiplication, and division",
            difficulty_level="Easy",
            dataset_size=30,
            model_configurations={
                "model": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
                "temperature": [0.0, 0.1, 0.3],
                "max_tokens": [50, 100],
            },
            metrics=[
                ProblemMetric("accuracy", "Exact answer correctness", True, 1.0, ".1%"),
                ProblemMetric(
                    "calculation_accuracy",
                    "Mathematical calculation accuracy",
                    True,
                    1.0,
                    ".1%",
                ),
                ProblemMetric(
                    "format_compliance", "Proper answer formatting", True, 0.7, ".1%"
                ),
            ],
            optimization_objectives=["accuracy"],
            expected_model_ranking=["gpt-4o", "gpt-4o-mini", "gpt-3.5-turbo"],
        )

    def __init__(self, config: Optional[ProblemConfig] = None):
        if config is None:
            config = self.get_default_config()
        super().__init__(config)

    def create_dataset(self) -> Dataset:
        """Create the evaluation dataset for basic arithmetic."""
        examples_data = [
            # Easy addition
            {
                "problem": "What is 5 + 3?",
                "answer": "8",
                "operation": "addition",
                "difficulty": "easy",
            },
            {
                "problem": "Calculate 12 + 8",
                "answer": "20",
                "operation": "addition",
                "difficulty": "easy",
            },
            {
                "problem": "Add 15 and 7",
                "answer": "22",
                "operation": "addition",
                "difficulty": "easy",
            },
            {
                "problem": "What is 9 + 6?",
                "answer": "15",
                "operation": "addition",
                "difficulty": "easy",
            },
            {
                "problem": "Sum of 11 and 14",
                "answer": "25",
                "operation": "addition",
                "difficulty": "easy",
            },
            # Easy subtraction
            {
                "problem": "What is 10 - 4?",
                "answer": "6",
                "operation": "subtraction",
                "difficulty": "easy",
            },
            {
                "problem": "Calculate 20 - 7",
                "answer": "13",
                "operation": "subtraction",
                "difficulty": "easy",
            },
            {
                "problem": "Subtract 5 from 18",
                "answer": "13",
                "operation": "subtraction",
                "difficulty": "easy",
            },
            # Easy multiplication
            {
                "problem": "What is 6 × 4?",
                "answer": "24",
                "operation": "multiplication",
                "difficulty": "easy",
            },
            {
                "problem": "Calculate 3 * 7",
                "answer": "21",
                "operation": "multiplication",
                "difficulty": "easy",
            },
            {
                "problem": "Multiply 8 by 5",
                "answer": "40",
                "operation": "multiplication",
                "difficulty": "easy",
            },
            # Easy division
            {
                "problem": "What is 20 ÷ 4?",
                "answer": "5",
                "operation": "division",
                "difficulty": "easy",
            },
            {
                "problem": "Calculate 15 / 3",
                "answer": "5",
                "operation": "division",
                "difficulty": "easy",
            },
            {
                "problem": "Divide 36 by 6",
                "answer": "6",
                "operation": "division",
                "difficulty": "easy",
            },
            # Medium problems
            {
                "problem": "What is 47 + 38?",
                "answer": "85",
                "operation": "addition",
                "difficulty": "medium",
            },
            {
                "problem": "Calculate 123 - 57",
                "answer": "66",
                "operation": "subtraction",
                "difficulty": "medium",
            },
            {
                "problem": "What is 13 × 12?",
                "answer": "156",
                "operation": "multiplication",
                "difficulty": "medium",
            },
            {
                "problem": "Calculate 144 ÷ 12",
                "answer": "12",
                "operation": "division",
                "difficulty": "medium",
            },
            {
                "problem": "Add 256 and 189",
                "answer": "445",
                "operation": "addition",
                "difficulty": "medium",
            },
            {
                "problem": "What is 500 - 237?",
                "answer": "263",
                "operation": "subtraction",
                "difficulty": "medium",
            },
            # Hard problems (multi-step)
            {
                "problem": "What is (15 + 8) × 3?",
                "answer": "69",
                "operation": "mixed",
                "difficulty": "hard",
            },
            {
                "problem": "Calculate 100 - (25 × 2)",
                "answer": "50",
                "operation": "mixed",
                "difficulty": "hard",
            },
            {
                "problem": "What is 48 ÷ 6 + 15?",
                "answer": "23",
                "operation": "mixed",
                "difficulty": "hard",
            },
            {
                "problem": "Calculate (84 ÷ 7) - 5",
                "answer": "7",
                "operation": "mixed",
                "difficulty": "hard",
            },
            # More medium problems to reach 30
            {
                "problem": "What is 67 + 44?",
                "answer": "111",
                "operation": "addition",
                "difficulty": "medium",
            },
            {
                "problem": "Calculate 200 - 78",
                "answer": "122",
                "operation": "subtraction",
                "difficulty": "medium",
            },
            {
                "problem": "What is 16 × 11?",
                "answer": "176",
                "operation": "multiplication",
                "difficulty": "medium",
            },
            {
                "problem": "Divide 168 by 14",
                "answer": "12",
                "operation": "division",
                "difficulty": "medium",
            },
            {
                "problem": "What is 99 + 87?",
                "answer": "186",
                "operation": "addition",
                "difficulty": "medium",
            },
            {
                "problem": "Calculate 300 - 145",
                "answer": "155",
                "operation": "subtraction",
                "difficulty": "medium",
            },
        ]

        examples = []
        for i, data in enumerate(examples_data):
            example = EvaluationExample(
                input_data={"problem": data["problem"]},
                expected_output=data["answer"],
                metadata={
                    "difficulty": data["difficulty"],
                    "operation": data["operation"],
                    "example_id": f"arithmetic_{i + 1:03d}",
                },
            )
            examples.append(example)

        return Dataset(
            examples=examples,
            name="Basic Arithmetic",
            description="Basic arithmetic problems including addition, subtraction, multiplication, and division",
        )

    def create_function(self) -> Callable:
        """Create the base function to optimize."""

        def solve_arithmetic(problem: str) -> str:
            """Solve basic arithmetic problems."""
            llm = ChatOpenAI(
                model="gpt-3.5-turbo",
                temperature=0.0,
                model_kwargs={"max_tokens": 50},
            )

            prompt_template = ChatPromptTemplate.from_messages(
                [
                    (
                        "system",
                        """You are a calculator that solves basic arithmetic problems.
Provide only the numerical answer, no explanation or work shown.
If the problem involves decimals, round to 2 decimal places.""",
                    ),
                    ("human", "{problem}"),
                ]
            )

            chain = LLMChain(llm=llm, prompt=prompt_template)
            result = chain.invoke({"problem": problem})["text"]

            # Clean the result to get just the number
            result = result.strip()
            # Remove any non-numeric characters except . and -
            import re

            result = re.sub(r"[^0-9.-]", "", result)

            return result

        return solve_arithmetic

    def create_optimized_function(self) -> Callable:
        """Create the optimized arithmetic solver."""

        @traigent.optimize(
            eval_dataset=self.create_temporary_dataset_file(),
            objectives=self.get_optimization_objectives(),
            configuration_space=self.get_configuration_space(),
            auto_override_frameworks=True,
            framework_targets=["langchain_openai.ChatOpenAI"],
            execution_mode="edge_analytics",
        )
        def solve_arithmetic_optimized(problem: str) -> str:
            """Optimized arithmetic problem solver."""
            llm = ChatOpenAI(
                model="gpt-3.5-turbo",  # Will be overridden by Traigent
                temperature=0.0,  # Will be overridden by Traigent
                model_kwargs={"max_tokens": 50},  # Will be overridden by Traigent
            )

            prompt_template = ChatPromptTemplate.from_messages(
                [
                    (
                        "system",
                        """You are a calculator that solves basic arithmetic problems.
Provide only the numerical answer, no explanation or work shown.
If the problem involves decimals, round to 2 decimal places.""",
                    ),
                    ("human", "{problem}"),
                ]
            )

            chain = LLMChain(llm=llm, prompt=prompt_template)
            result = chain.invoke({"problem": problem})["text"]

            # Clean the result to get just the number
            result = result.strip()
            # Remove any non-numeric characters except . and -
            import re

            result = re.sub(r"[^0-9.-]", "", result)

            return result

        return solve_arithmetic_optimized

    def evaluate_custom_metrics(
        self,
        outputs: List[Any],
        expected_outputs: List[Any],
        errors: List[Optional[str]],
    ) -> Dict[str, float]:
        """Compute arithmetic-specific metrics."""
        metrics = {}

        # Get dataset for metadata access
        self.get_dataset()

        # Standard accuracy
        correct = 0
        total = 0
        calculation_correct = 0
        format_compliant = 0

        for _i, (output, expected, error) in enumerate(
            zip(outputs, expected_outputs, errors)
        ):
            if error is None and expected is not None and output:
                total += 1

                # Clean output and expected
                output_clean = str(output).strip()
                expected_clean = str(expected).strip()

                # Exact match
                if output_clean == expected_clean:
                    correct += 1
                    calculation_correct += 1
                else:
                    # Try numeric comparison
                    try:
                        output_num = float(output_clean)
                        expected_num = float(expected_clean)
                        if (
                            abs(output_num - expected_num) < 0.01
                        ):  # Allow small rounding differences
                            correct += 1
                            calculation_correct += 1
                    except Exception:
                        pass

                # Format compliance - check if it's a clean number
                import re

                if re.match(r"^-?\d+(\.\d+)?$", output_clean):
                    format_compliant += 1

        metrics["accuracy"] = correct / total if total > 0 else 0.0
        metrics["calculation_accuracy"] = (
            calculation_correct / total if total > 0 else 0.0
        )
        metrics["format_compliance"] = format_compliant / total if total > 0 else 0.0

        return metrics


# Register this problem
register_problem("basic_arithmetic", BasicArithmeticProblem)
