"""
Provides evidence-based strategies and methods for quitting smoking, including behavioral techniques, nicotine replacement options, and support resources

This module implements a question_answering problem for LangChain optimization
using the Traigent framework.

Domain: medical
Difficulty: medium
Generated by: Traigent Problem Manager
"""

import random
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from examples.langchain_problems.base import ProblemConfig, ProblemDefinition
from . import register_problem


@dataclass
class SmokingCessationGuidanceConfig(ProblemConfig):
    """Configuration for smoking_cessation_guidance problem."""

    # Model configuration space
    model: str = "gpt-4o-mini"
    temperature: float = 0.3
    max_tokens: int = 260

    def get_config_space(self) -> Dict[str, List[Any]]:
        """Define the optimization search space."""
        return {
            "model": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
            "temperature": [
                0.1,
                0.16,
                0.22,
                0.28,
                0.34,
                0.4,
                0.46,
                0.52,
                0.58,
                0.64,
                0.7,
            ],
            "max_tokens": [self.max_tokens],
        }


class SmokingCessationGuidance(ProblemDefinition):
    """
    Provides evidence-based strategies and methods for quitting smoking, including behavioral techniques, nicotine replacement options, and support resources

    Problem Type: question_answering
    Domain: medical
    Difficulty: medium
    Examples: 25
    """

    def __init__(self):
        super().__init__()
        self.config = SmokingCessationGuidanceConfig()
        self.examples = self._load_examples()

    def _load_examples(self) -> List[Dict[str, Any]]:
        """Load the example dataset."""
        return [
            {
                "expected_output": "Generated by user request",
                "id": 1,
                "input_data": {
                    "text": "I've been smoking for 15 years and want to quit. What are the most effective "
                    "nicotine replacement therapies available, and how do I choose between patches, gum, "
                    "or lozenges?"
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_1",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 2,
                "input_data": {
                    "text": "What behavioral techniques can help me manage cravings when I'm trying to quit "
                    "smoking? I especially struggle with the after-meal cigarette habit."
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_2",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 3,
                "input_data": {
                    "text": "Are there any prescription medications that can help with smoking cessation? What "
                    "are the success rates compared to going cold turkey?"
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_3",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 4,
                "input_data": {
                    "text": "I'm planning to quit smoking next month. What support groups or online resources "
                    "would you recommend for someone who needs accountability and encouragement?"
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_4",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 5,
                "input_data": {
                    "text": "What's the best way to create a quit-smoking plan? Should I gradually reduce "
                    "cigarettes or stop all at once?"
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_5",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 6,
                "input_data": {
                    "text": "How can I handle withdrawal symptoms when quitting smoking? What should I expect in "
                    "the first few weeks?"
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_6",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 7,
                "input_data": {
                    "text": "My doctor mentioned varenicline for smoking cessation. How does it work and what "
                    "are the potential side effects?"
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_7",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 8,
                "input_data": {
                    "text": "What smartphone apps or digital tools have proven helpful for people trying to quit "
                    "smoking? I need something to track my progress."
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_8",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 9,
                "input_data": {
                    "text": "I've failed to quit smoking three times before. What different strategies should I "
                    "try this time to increase my chances of success?"
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_9",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "Generated by user request",
                "id": 10,
                "input_data": {
                    "text": "How can I prepare my environment for quitting smoking? What changes should I make "
                    "at home and work to avoid triggers?"
                },
                "metadata": {
                    "category": "medical",
                    "difficulty": "medium",
                    "domain_specific_info": "Generated for Provides evidence-based strategies and methods for "
                    "quitting smoking, including behavioral techniques, nicotine "
                    "replacement options, and support resources",
                    "pattern": "example_10",
                    "reasoning": "Example for question_answering task",
                },
            },
            {
                "expected_output": "emergency",
                "id": 11,
                "input_data": {
                    "patient_case": "Chest pain and shortness of breath",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "emergency",
                    "difficulty": "easy",
                    "domain": "medical",
                    "reasoning": "Easy medical case requiring emergency classification",
                },
            },
            {
                "expected_output": "test_results",
                "id": 13,
                "input_data": {
                    "patient_case": "Abnormal imaging results requiring specialist interpretation",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "test_results",
                    "difficulty": "hard",
                    "domain": "medical",
                    "reasoning": "Hard medical case requiring test_results classification",
                },
            },
            {
                "expected_output": "emergency",
                "id": 15,
                "input_data": {
                    "patient_case": "Severe allergic reaction requiring immediate attention",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "emergency",
                    "difficulty": "hard",
                    "domain": "medical",
                    "reasoning": "Hard medical case requiring emergency classification",
                },
            },
            {
                "expected_output": "test_results",
                "id": 17,
                "input_data": {
                    "patient_case": "Blood sugar levels elevated in recent home testing",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "test_results",
                    "difficulty": "medium",
                    "domain": "medical",
                    "reasoning": "Medium medical case requiring test_results classification",
                },
            },
            {
                "expected_output": "specialist_referral",
                "id": 19,
                "input_data": {
                    "patient_case": "Complex symptom pattern: fatigue, joint pain, and cognitive issues",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "specialist_referral",
                    "difficulty": "hard",
                    "domain": "medical",
                    "reasoning": "Hard medical case requiring specialist_referral classification",
                },
            },
            {
                "expected_output": "test_results",
                "id": 21,
                "input_data": {
                    "patient_case": "Blood sugar levels elevated in recent home testing",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "test_results",
                    "difficulty": "medium",
                    "domain": "medical",
                    "reasoning": "Medium medical case requiring test_results classification",
                },
            },
            {
                "expected_output": "test_results",
                "id": 23,
                "input_data": {
                    "patient_case": "Blood sugar levels elevated in recent home testing",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "test_results",
                    "difficulty": "medium",
                    "domain": "medical",
                    "reasoning": "Medium medical case requiring test_results classification",
                },
            },
            {
                "expected_output": "specialist_referral",
                "id": 25,
                "input_data": {
                    "patient_case": "Persistent headaches with vision changes over 2 weeks",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "specialist_referral",
                    "difficulty": "medium",
                    "domain": "medical",
                    "reasoning": "Medium medical case requiring specialist_referral classification",
                },
            },
            {
                "expected_output": "emergency",
                "id": 27,
                "input_data": {
                    "patient_case": "Severe allergic reaction requiring immediate attention",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "emergency",
                    "difficulty": "hard",
                    "domain": "medical",
                    "reasoning": "Hard medical case requiring emergency classification",
                },
            },
            {
                "expected_output": "prescription_request",
                "id": 29,
                "input_data": {
                    "patient_case": "Medication side effects causing nausea and dizziness",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "prescription_request",
                    "difficulty": "medium",
                    "domain": "medical",
                    "reasoning": "Medium medical case requiring prescription_request classification",
                },
            },
            {
                "expected_output": "specialist_referral",
                "id": 31,
                "input_data": {
                    "patient_case": "Referral needed for dermatologist",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "specialist_referral",
                    "difficulty": "easy",
                    "domain": "medical",
                    "reasoning": "Easy medical case requiring specialist_referral classification",
                },
            },
            {
                "expected_output": "prescription_request",
                "id": 33,
                "input_data": {
                    "patient_case": "Medication interaction concerns with new cardiac prescription",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "prescription_request",
                    "difficulty": "hard",
                    "domain": "medical",
                    "reasoning": "Hard medical case requiring prescription_request classification",
                },
            },
            {
                "expected_output": "prescription_request",
                "id": 35,
                "input_data": {
                    "patient_case": "Medication side effects causing nausea and dizziness",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "prescription_request",
                    "difficulty": "medium",
                    "domain": "medical",
                    "reasoning": "Medium medical case requiring prescription_request classification",
                },
            },
            {
                "expected_output": "emergency",
                "id": 37,
                "input_data": {
                    "patient_case": "Chest pain and shortness of breath",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "emergency",
                    "difficulty": "easy",
                    "domain": "medical",
                    "reasoning": "Easy medical case requiring emergency classification",
                },
            },
            {
                "expected_output": "emergency",
                "id": 39,
                "input_data": {
                    "patient_case": "Chest pain and shortness of breath",
                    "urgency": "standard",
                },
                "metadata": {
                    "category": "emergency",
                    "difficulty": "easy",
                    "domain": "medical",
                    "reasoning": "Easy medical case requiring emergency classification",
                },
            },
        ]

    def get_dataset(self) -> Any:
        """Return the dataset for this problem."""
        return self.examples

    def create_dataset(self, subset_size: Optional[int] = None) -> List[Dict[str, Any]]:
        """Create dataset for optimization."""
        dataset = self.examples.copy()

        if subset_size and subset_size < len(dataset):
            random.shuffle(dataset)
            dataset = dataset[:subset_size]

        return dataset

    def create_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create the base function to optimize."""

        def process_smoking_cessation_guidance(
            input_data: Dict[str, Any], config: SmokingCessationGuidanceConfig
        ) -> str:
            """
            Process provides evidence-based strategies and methods for quitting smoking, including behavioral techniques, nicotine replacement options, and support resources
            """
            from langchain.schema import HumanMessage
            from langchain_openai import ChatOpenAI

            # Initialize the model with current configuration
            llm = ChatOpenAI(
                model=config.model,
                temperature=config.temperature,
                model_kwargs={"max_tokens": config.max_tokens},
            )

            # Create prompt based on problem type
            # Default prompt
            text = str(input_data)
            prompt = f"Process the following input: {text}"

            # Get response
            response = llm.invoke([HumanMessage(content=prompt)])

            # Extract and format result
            # Extract text result
            result = response.content.strip()

            return result

        return process_smoking_cessation_guidance

    def create_optimized_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create optimized version using Traigent."""
        import traigent

        base_function = self.create_function(dataset)

        @traigent.optimize(
            config_class=SmokingCessationGuidanceConfig,
            dataset=dataset,
            metrics=["accuracy", "quality", "relevance"],
        )
        def optimized_process_smoking_cessation_guidance(
            input_data: Dict[str, Any], config: SmokingCessationGuidanceConfig
        ) -> str:
            return base_function(input_data, config)

        return optimized_process_smoking_cessation_guidance

    def evaluate_custom_metrics(self, results: List[Any]) -> Dict[str, float]:
        """Calculate custom evaluation metrics."""
        if not results:
            return {}

        metrics = {}

        # Basic metrics
        total_results = len(results)
        if total_results == 0:
            return {}

        successful_results = [r for r in results if r.success]
        success_rate = len(successful_results) / total_results
        metrics["success_rate"] = success_rate
        # Custom metric: accuracy
        metrics["accuracy"] = 0.0  # Implement custom calculation
        # Custom metric: quality
        metrics["quality"] = 0.0  # Implement custom calculation
        # Custom metric: relevance
        metrics["relevance"] = 0.0  # Implement custom calculation

        return metrics


# Example usage and testing
if __name__ == "__main__":
    problem = SmokingCessationGuidance()
    dataset = problem.create_dataset(subset_size=5)

    print(f"Problem: {problem.__class__.__name__}")
    print(f"Dataset size: {len(dataset)}")
    print(f"Sample example: {dataset[0] if dataset else 'No examples'}")

    # Test base function
    base_func = problem.create_function(dataset)
    if dataset:
        result = base_func(dataset[0], problem.config)
        print(f"Sample result: {result}")


# Register this problem
register_problem("smoking_cessation_guidance", SmokingCessationGuidance)
