"""
Code Generator for LangChain Optimization Problems.

This module generates Python code for problem modules based on analyzed descriptions,
examples, and domain patterns. It creates complete, ready-to-use problem modules
that follow the Traigent SDK patterns and conventions.
"""

import ast
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .example_generator import GeneratedExample


@dataclass
class CodeGenerationConfig:
    """Configuration for code generation."""

    name: str
    description: str
    domain: str
    difficulty: str
    output_type: str
    models: list[str]
    temperature_range: list[float]
    max_tokens: int | None = None
    custom_metrics: list[str] | None = None


class CodeGenerator:
    """
    Generates Python code for LangChain optimization problems.

    Creates complete problem modules including class definitions,
    example datasets, optimization functions, and evaluation metrics.
    """

    def __init__(self):
        """Initialize the code generator."""
        self.base_template = self._load_base_template()

    def _load_base_template(self) -> str:
        """Load the base problem template."""
        return '''"""
{description}

This module implements a {output_type} problem for LangChain optimization
using the Traigent framework.

Domain: {domain}
Difficulty: {difficulty}
Generated by: Traigent Problem Manager
"""

import random
from typing import Any, Dict, List, Tuple, Optional
from dataclasses import dataclass

from langchain_problems.base import ProblemDefinition, ProblemConfig, ProblemMetric


@dataclass
class {class_name}Config(ProblemConfig):
    """Configuration for {name} problem."""

    def __init__(self):
        """Initialize configuration with required parameters."""
        super().__init__(
            name="{name}",
            description="{description}",
            difficulty_level="{difficulty}",
            dataset_size={example_count},
            model_configurations={{
                "model": {models_list},
                "temperature": {temperature_range},
                "max_tokens": [{max_tokens}]
            }},
            metrics={problem_metrics},
            optimization_objectives={optimization_objectives}
        )

        # Set default model configuration
        self.model = "gpt-4o-mini"
        self.temperature = 0.3
        self.max_tokens = {max_tokens}

    def get_config_space(self) -> Dict[str, List[Any]]:
        """Define the optimization search space."""
        return self.model_configurations


class {class_name}(ProblemDefinition):
    """
    {description}

    Problem Type: {output_type}
    Domain: {domain}
    Difficulty: {difficulty}
    Examples: {example_count}
    """

    def __init__(self, config: Optional[{class_name}Config] = None):
        """Initialize with optional config."""
        self.config = config or {class_name}Config()
        super().__init__(self.config)
        self.examples = self._load_examples()

    def _load_examples(self) -> List[Dict[str, Any]]:
        """Load the example dataset."""
        return {examples_data}

    def get_dataset(self) -> Any:
        """Return the dataset for this problem."""
        return self.examples

    def create_dataset(self, subset_size: Optional[int] = None) -> List[Dict[str, Any]]:
        """Create dataset for optimization."""
        dataset = self.examples.copy()

        if subset_size and subset_size < len(dataset):
            random.shuffle(dataset)
            dataset = dataset[:subset_size]

        return dataset

    def create_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create the base function to optimize."""

        def {function_name}(input_data: Dict[str, Any], config: {class_name}Config) -> str:
            """
            {function_description}
            """
            from langchain_openai import ChatOpenAI
            from langchain.schema import HumanMessage

            # Initialize the model with current configuration
            llm = ChatOpenAI(
                model=config.model,
                temperature=config.temperature,
                max_tokens=config.max_tokens)

            # Create prompt based on problem type
            {prompt_generation}

            # Get response
            response = llm.invoke([HumanMessage(content=prompt)])

            # Extract and format result
            {result_processing}

            return result

        return {function_name}

    def create_optimized_function(self, dataset: List[Dict[str, Any]]) -> callable:
        """Create optimized version using Traigent."""
        import traigent

        base_function = self.create_function(dataset)

        @traigent.optimize(
            config_class={class_name}Config,
            dataset=dataset,
            metrics={metrics_list}
        )
        def optimized_{function_name}(input_data: Dict[str, Any], config: {class_name}Config) -> str:
            return base_function(input_data, config)

        return optimized_{function_name}

    def evaluate_custom_metrics(self, results: List[Any]) -> Dict[str, float]:
        """Calculate custom evaluation metrics."""
        if not results:
            return {{}}

        metrics = {{}}

        {custom_metrics_calculation}

        return metrics


# Example usage and testing
if __name__ == "__main__":
    problem = {class_name}()
    dataset = problem.create_dataset(subset_size=5)

    print(f"Problem: {{problem.__class__.__name__}}")
    print(f"Dataset size: {{len(dataset)}}")
    print(f"Sample example: {{dataset[0] if dataset else 'No examples'}}")

    # Test base function
    base_func = problem.create_function(dataset)
    if dataset:
        result = base_func(dataset[0], problem.config)
        print(f"Sample result: {{result}}")


# Register this problem
from . import register_problem
register_problem("{name}", {class_name})
'''

    async def generate_problem_module(
        self,
        name: str,
        description: str,
        domain: str,
        difficulty: str,
        examples: list[Any],  # Can be GeneratedExample objects or dicts
        output_type: str,
        models: list[str],
        temperature_range: list[float],
        max_tokens: int | None = None,
        custom_metrics: list[str] | None = None,
    ) -> str:
        """
        Generate a complete problem module.

        Args:
            name: Problem name
            description: Problem description
            domain: Problem domain
            difficulty: Difficulty level
            examples: Generated examples
            output_type: Type of problem (classification, generation, etc.)
            models: List of models to use
            temperature_range: Temperature range for optimization
            max_tokens: Max tokens (auto-determined if None)
            custom_metrics: Custom metrics list

        Returns:
            Complete Python module code
        """
        # Format class name
        class_name = self._format_class_name(name)

        # Determine max tokens if not specified
        if max_tokens is None:
            max_tokens = self._determine_max_tokens(output_type, domain)

        # Convert examples to data format
        examples_data = self._format_examples_data(examples)

        # Generate prompt logic based on output type
        prompt_generation = self._generate_prompt_logic(output_type, domain)

        # Generate result processing logic
        result_processing = self._generate_result_processing(output_type)

        # Generate custom metrics calculation
        custom_metrics_calc = self._generate_custom_metrics(output_type, custom_metrics or [])

        # Generate function description
        function_description = self._generate_function_description(description, output_type)

        # Generate temperature range as proper list
        temp_start, temp_end = temperature_range
        temp_step = (temp_end - temp_start) / 10
        temp_values = [round(temp_start + i * temp_step, 2) for i in range(11)]

        # Generate problem metrics
        all_metrics = custom_metrics or self._get_default_metrics(output_type)
        problem_metrics = []
        for metric_name in all_metrics:
            problem_metrics.append(
                {
                    "name": metric_name,
                    "description": f"Measure {metric_name} for {output_type} problem",
                    "higher_is_better": True,
                    "weight": 1.0,
                }
            )

        # Generate optimization objectives
        optimization_objectives = all_metrics[:2] if len(all_metrics) >= 2 else all_metrics

        # Format the template
        code = self.base_template.format(
            class_name=class_name,
            name=name,
            description=description,
            domain=domain,
            difficulty=difficulty,
            output_type=output_type,
            example_count=len(examples),
            max_tokens=max_tokens,
            models_list=json.dumps(models),
            temperature_range=json.dumps(temp_values),
            examples_data=examples_data,
            function_name=self._generate_function_name(name, output_type),
            function_description=function_description,
            prompt_generation=prompt_generation,
            result_processing=result_processing,
            metrics_list=json.dumps(all_metrics),
            custom_metrics_calculation=custom_metrics_calc,
            problem_metrics=json.dumps(problem_metrics),
            optimization_objectives=json.dumps(optimization_objectives),
        )

        return code

    async def add_examples_to_module(
        self, problem_name: str, new_examples: list[GeneratedExample]
    ) -> str:
        """
        Add examples to an existing problem module.

        Args:
            problem_name: Name of existing problem
            new_examples: New examples to add

        Returns:
            Updated module code
        """
        # Read existing module
        module_path = Path(f"traigent_ui/langchain_problems/{problem_name}.py")
        if not module_path.exists():
            raise FileNotFoundError(f"Problem module not found: {module_path}")

        existing_code = module_path.read_text()

        # Extract existing examples
        existing_examples = self._extract_examples_from_code(existing_code)

        # Combine with new examples
        all_examples = existing_examples + [
            self._convert_generated_to_dict(ex) for ex in new_examples
        ]

        # Format new examples data
        new_examples_data = self._format_examples_data_from_dicts(all_examples)

        # Replace examples in code
        updated_code = self._replace_examples_in_code(
            existing_code, new_examples_data, len(all_examples)
        )

        return updated_code

    def _format_class_name(self, name: str) -> str:
        """Format problem name as class name."""
        # Convert to PascalCase
        words = name.replace("_", " ").replace("-", " ").split()
        return "".join(word.capitalize() for word in words)

    def _determine_max_tokens(self, output_type: str, domain: str) -> int:
        """Determine appropriate max tokens."""
        base_tokens = {
            "classification": 50,
            "generation": 500,
            "analysis": 300,
            "structured": 200,
        }

        domain_multipliers = {
            "legal": 1.5,
            "medical": 1.3,
            "technical": 1.2,
            "financial": 1.2,
            "customer_service": 1.0,
            "educational": 1.1,
            "general": 1.0,
        }

        base = base_tokens.get(output_type, 200)
        multiplier = domain_multipliers.get(domain, 1.0)

        return int(base * multiplier)

    def _format_examples_data(self, examples: list[Any]) -> str:
        """Format examples as Python data structure."""
        examples_dict = []

        for i, example in enumerate(examples):
            # Handle both GeneratedExample objects and dicts
            if isinstance(example, dict):
                # It's already a dict
                example_dict = {
                    "id": example.get("id", i + 1),
                    "input_data": example.get("input_data", {}),
                    "expected_output": example.get("expected_output", ""),
                    "metadata": {
                        "difficulty": example.get("difficulty", "medium"),
                        "reasoning": example.get("reasoning", ""),
                        **example.get("metadata", {}),
                    },
                }
            else:
                # It's a GeneratedExample object
                example_dict = {
                    "id": i + 1,
                    "input_data": getattr(example, "input_data", {}),
                    "expected_output": getattr(example, "expected_output", ""),
                    "metadata": {
                        "difficulty": getattr(example, "difficulty", "medium"),
                        "reasoning": getattr(example, "reasoning", ""),
                        **getattr(example, "metadata", {}),
                    },
                }
            examples_dict.append(example_dict)

        # Use proper indentation for Python code
        import pprint

        formatted = pprint.pformat(examples_dict, indent=4, width=120)
        # Add proper indentation for the template
        lines = formatted.split("\n")
        indented_lines = ["        " + line if line.strip() else line for line in lines]
        return "\n".join(indented_lines)

    def _format_examples_data_from_dicts(self, examples: list[dict]) -> str:
        """Format examples from dictionaries."""
        # Re-number the IDs
        for i, example in enumerate(examples):
            example["id"] = i + 1

        return json.dumps(examples, indent=8)

    def _generate_prompt_logic(self, output_type: str, domain: str) -> str:
        """Generate prompt creation logic based on output type."""
        if output_type == "classification":
            categories_list = self._get_domain_categories(domain)
            categories_str = ", ".join(f'"{cat}"' for cat in categories_list)
            return f'''# Classification prompt
            categories = {categories_list}
            text = input_data.get('text', input_data.get('query', str(input_data)))

            prompt = f"""Classify the following text into one of these categories: {categories_str}

Text: {{text}}

Category:"""'''

        elif output_type == "generation":
            return '''# Generation prompt
            prompt_text = input_data.get('prompt', input_data.get('text', str(input_data)))
            context = input_data.get('context', '')

            prompt = f"""Generate content based on the following prompt:

Prompt: {prompt_text}
{f"Context: {context}" if context else ""}

Generated content:"""'''

        elif output_type == "analysis":
            return '''# Analysis prompt
            document = input_data.get('document', input_data.get('text', str(input_data)))
            analysis_type = input_data.get('analysis_type', 'comprehensive')

            prompt = f"""Analyze the following document:

Document: {document}
Analysis Type: {analysis_type}

Provide a detailed analysis including key points, insights, and conclusions:"""'''

        elif output_type == "structured":
            return '''# Structured extraction prompt
            text = input_data.get('text', str(input_data))
            format_type = input_data.get('format', 'structured')

            prompt = f"""Extract structured information from the following text:

Text: {text}
Format: {format_type}

Extracted information (return as JSON):"""'''

        else:
            return '''# Default prompt
            text = str(input_data)
            prompt = f"Process the following input: {text}"'''

    def _generate_result_processing(self, output_type: str) -> str:
        """Generate result processing logic."""
        if output_type == "classification":
            return """# Extract classification result
            result = response.content.strip()
            # Clean up result to get just the category
            result = result.split('\\n')[0].strip()"""

        elif output_type == "structured":
            return """# Parse structured result
            result_text = response.content.strip()
            try:
                # Try to parse as JSON
                import json
                result = json.loads(result_text)
            except Exception:
                # Fall back to text result
                result = result_text"""

        else:
            return """# Extract text result
            result = response.content.strip()"""

    def _generate_custom_metrics(self, output_type: str, custom_metrics: list[str]) -> str:
        """Generate custom metrics calculation."""
        base_metrics = """# Basic metrics
        total_results = len(results)
        if total_results == 0:
            return {}

        successful_results = [r for r in results if r.success]
        success_rate = len(successful_results) / total_results
        metrics['success_rate'] = success_rate"""

        if output_type == "classification":
            metrics = (
                base_metrics
                + """

        # Classification-specific metrics
        correct_predictions = 0
        for result in successful_results:
            expected = result.expected_output
            actual = result.result
            if str(expected).strip().lower() == str(actual).strip().lower():
                correct_predictions += 1

        if successful_results:
            metrics['accuracy'] = correct_predictions / len(successful_results)
        else:
            metrics['accuracy'] = 0.0"""
            )

        elif output_type == "generation":
            metrics = (
                base_metrics
                + """

        # Generation-specific metrics
        avg_length = 0
        if successful_results:
            total_length = sum(len(str(r.result)) for r in successful_results)
            avg_length = total_length / len(successful_results)
        metrics['avg_generation_length'] = avg_length"""
            )

        else:
            metrics = base_metrics

        # Add custom metrics
        for metric in custom_metrics:
            metrics += f"""
        # Custom metric: {metric}
        metrics['{metric}'] = 0.0  # Implement custom calculation"""

        return metrics

    def _generate_function_description(self, description: str, output_type: str) -> str:
        """Generate function description."""
        action_words = {
            "classification": "Classify",
            "generation": "Generate",
            "analysis": "Analyze",
            "structured": "Extract structured data from",
        }

        action = action_words.get(output_type, "Process")
        return f"{action} {description.lower()}"

    def _generate_function_name(self, name: str, output_type: str) -> str:
        """Generate function name."""
        action_prefixes = {
            "classification": "classify",
            "generation": "generate",
            "analysis": "analyze",
            "structured": "extract",
        }

        prefix = action_prefixes.get(output_type, "process")
        clean_name = name.replace("-", "_").replace(" ", "_")
        return f"{prefix}_{clean_name}"

    def _get_default_metrics(self, output_type: str) -> list[str]:
        """Get default metrics for output type."""
        # Map output types to problem types
        problem_type_metrics = {
            "classification": ["accuracy", "precision", "recall"],
            "generation": ["fluency", "coherence", "relevance"],
            "reasoning": ["answer_accuracy", "reasoning_validity", "step_correctness"],
            "question_answering": [
                "answer_relevance",
                "answer_accuracy",
                "exact_match",
            ],
            "information_extraction": [
                "extraction_f1",
                "extraction_precision",
                "extraction_recall",
            ],
            "summarization": ["summary_quality", "information_coverage", "conciseness"],
            "ranking_retrieval": ["ndcg", "map", "mrr"],
            "translation_transformation": [
                "transformation_accuracy",
                "output_validity",
                "semantic_preservation",
            ],
            "code_generation": ["syntax_correctness", "functionality", "code_quality"],
            "analysis": ["completeness_score", "insight_quality", "accuracy"],
            "structured": ["extraction_accuracy", "schema_compliance", "completeness"],
        }

        # Get metrics for the output type
        metrics = problem_type_metrics.get(output_type, ["quality", "accuracy", "relevance"])

        # Always include success_rate as base metric
        return ["success_rate"] + metrics[:3]  # Limit to 4 metrics total

    def _get_domain_categories(self, domain: str) -> list[str]:
        """Get categories for domain."""
        domain_categories = {
            "customer_service": [
                "billing_issue",
                "technical_support",
                "product_inquiry",
                "shipping_inquiry",
                "return_request",
                "account_support",
            ],
            "legal": [
                "contract_review",
                "compliance_check",
                "risk_assessment",
                "liability_analysis",
                "regulatory_review",
            ],
            "medical": [
                "emergency",
                "routine_checkup",
                "specialist_referral",
                "prescription_request",
                "test_results",
            ],
            "technical": [
                "bug_report",
                "feature_request",
                "performance_issue",
                "security_concern",
                "documentation_update",
            ],
            "financial": [
                "loan_application",
                "investment_advice",
                "fraud_detection",
                "credit_assessment",
                "insurance_claim",
            ],
            "educational": [
                "course_content",
                "assessment",
                "student_support",
                "curriculum_design",
                "learning_outcome",
            ],
        }

        return domain_categories.get(
            domain, ["category_a", "category_b", "category_c", "category_d"]
        )

    def _extract_examples_from_code(self, code: str) -> list[dict]:
        """Extract examples from existing code."""
        # Simple extraction - look for the examples list
        import re

        # Find the examples data in the _load_examples method
        pattern = r"return\s+(\[.*?\])"
        match = re.search(pattern, code, re.DOTALL)

        if match:
            try:
                examples_str = match.group(1)
                # Use ast.literal_eval for safe evaluation
                examples = ast.literal_eval(examples_str)
                return examples
            except Exception:
                pass

        return []

    def _convert_generated_to_dict(self, example: GeneratedExample) -> dict:
        """Convert GeneratedExample to dictionary format."""
        return {
            "id": 0,  # Will be set later
            "input_data": example.input_data,
            "expected_output": example.expected_output,
            "metadata": {
                "difficulty": example.difficulty,
                "reasoning": example.reasoning,
                **example.metadata,
            },
        }

    def _replace_examples_in_code(self, code: str, new_examples_data: str, total_count: int) -> str:
        """Replace examples data in existing code."""
        import re

        # Replace the examples data
        pattern = r"return\s+\[.*?\]"
        replacement = f"return {new_examples_data}"
        code = re.sub(pattern, replacement, code, flags=re.DOTALL)

        # Update example count in class docstring
        pattern = r"Examples:\s+\d+"
        replacement = f"Examples: {total_count}"
        code = re.sub(pattern, replacement, code)

        return code
